services:
  app:
    image: ghcr.io/pattaradanai888/coachcall-backend:main  # Will be updated by CI/CD
    # build: .  # Use local build for testing
    container_name: fastapi-backend
    ports:
      - "8000:8000"
    environment:
      - PROJECT_NAME=${PROJECT_NAME:-FastAPI Backend}
      - ENVIRONMENT=${ENVIRONMENT:-production}
      - DATABASE_URL=${DATABASE_URL}
      - TEST_DATABASE_URL=${TEST_DATABASE_URL}
      - DEPLOYMENT_DATABASE_URL=${DEPLOYMENT_DATABASE_URL}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_ALGORITHM=${JWT_ALGORITHM:-HS256}
      - TOKEN_TYPE=${TOKEN_TYPE:-bearer}
      - ACCESS_TOKEN_EXPIRE_MINUTES=${ACCESS_TOKEN_EXPIRE_MINUTES:-30}
      - REFRESH_TOKEN_EXPIRE_MINUTES=${REFRESH_TOKEN_EXPIRE_MINUTES:-10080}
      - AZURE_STORAGE_ACCOUNT=${AZURE_STORAGE_ACCOUNT}
      - AZURE_STORAGE_KEY=${AZURE_STORAGE_KEY}
      - AZURE_CONTAINER_NAME=${AZURE_CONTAINER_NAME}
      - COMMUNICATION_SERVICES_CONNECTION_STRING=${COMMUNICATION_SERVICES_CONNECTION_STRING}
      - SENDER_ADDRESS=${SENDER_ADDRESS}
      - CORS_ORIGINS=${CORS_ORIGINS}
    env_file:
      - .env  # Fallback to local .env file
    restart: unless-stopped
    volumes:
      - app_logs:/app/logs
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health-check"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    # Memory limits for 1GB VM optimization
    deploy:
      resources:
        limits:
          memory: 400M  # Hard limit - enough for FastAPI
        reservations:
          memory: 200M  # Guaranteed memory

  # All monitoring services removed for cost optimization and reduced VM resource usage
  # FastAPI application now runs without any monitoring overhead

networks:
  app-network:
    driver: bridge

volumes:
  app_logs:
  # All monitoring volumes removed for cost optimization
  # prometheus_data: removed
  # grafana_data: removed  
  # loki_data: removed
