"""Add fields to TaskCompletion model to store the extra data. A JSON field

Revision ID: 2c9fdf1d980b
Revises: f14ba2d961d8
Create Date: 2025-06-26 17:00:26.482575

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2c9fdf1d980b'
down_revision: Union[str, None] = 'f14ba2d961d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task_completions', sa.Column('final_score', sa.Numeric(precision=5, scale=2), nullable=False))
    op.add_column('task_completions', sa.Column('scores_breakdown', sa.JSON(), nullable=True))
    op.add_column('task_completions', sa.Column('notes', sa.String(), nullable=True))
    op.add_column('task_completions', sa.Column('time_seconds', sa.Integer(), nullable=True))
    op.drop_column('task_completions', 'score')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task_completions', sa.Column('score', sa.NUMERIC(precision=4, scale=2), autoincrement=False, nullable=False))
    op.drop_column('task_completions', 'time_seconds')
    op.drop_column('task_completions', 'notes')
    op.drop_column('task_completions', 'scores_breakdown')
    op.drop_column('task_completions', 'final_score')
    # ### end Alembic commands ###
