"""Add completed_at to Session and add index

Revision ID: 43a408b2db7e
Revises: 2594308e33b8
Create Date: 2025-07-04 15:35:24.929345

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '43a408b2db7e'
down_revision: Union[str, None] = '2594308e33b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sessions', sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index('ix_sessions_status_scheduled_date', 'sessions', ['status', 'scheduled_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_sessions_status_scheduled_date', table_name='sessions')
    op.drop_column('sessions', 'completed_at')
    # ### end Alembic commands ###
