"""update relation of session and course to set ondelete = 'SET NULL'

Revision ID: 4c909b4b64d8
Revises: 59a56e19b41f
Create Date: 2025-06-29 22:53:47.802338

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4c909b4b64d8'
down_revision: Union[str, None] = '59a56e19b41f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('sessions_course_id_fkey', 'sessions', type_='foreignkey')
    op.create_foreign_key(None, 'sessions', 'courses', ['course_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sessions', type_='foreignkey')
    op.create_foreign_key('sessions_course_id_fkey', 'sessions', 'courses', ['course_id'], ['id'])
    # ### end Alembic commands ###
