"""Add total session time is the session table

Revision ID: 59a56e19b41f
Revises: 2c9fdf1d980b
Create Date: 2025-06-27 11:51:38.695547

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '59a56e19b41f'
down_revision: Union[str, None] = '2c9fdf1d980b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sessions', sa.Column('total_session_time_seconds', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sessions', 'total_session_time_seconds')
    # ### end Alembic commands ###
