"""Fix uuid

Revision ID: 76f1cfa204f7
Revises: 9615efdea308
Create Date: 2025-06-11 11:13:08.126395

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '76f1cfa204f7'
down_revision: Union[str, None] = '9615efdea308'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('athletes', 'uuid',
               existing_type=sa.VARCHAR(length=36),
               type_=sa.UUID(),
               postgresql_using='uuid::uuid',
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('athletes', 'uuid',
               existing_type=sa.UUID(),
               type_=sa.VARCHAR(length=36),
               postgresql_using='uuid::text',
               nullable=True)
    # ### end Alembic commands ###
