"""remove display-name from athlete table

Revision ID: 9615efdea308
Revises: ba8f0d64f91b
Create Date: 2025-06-04 18:05:38.931885

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9615efdea308'
down_revision: Union[str, None] = 'ba8f0d64f91b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('athletes', 'display_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('athletes', sa.Column('display_name', sa.VARCHAR(length=150), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
