"""add is_archived in course and status in session

Revision ID: 9ab5c845ffb3
Revises: 57b37a195927
Create Date: 2025-06-21 15:40:35.925306

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9ab5c845ffb3'
down_revision: Union[str, None] = '57b37a195927'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('courses', sa.Column('is_archived', sa.Boolean(), nullable=True))
    op.add_column('sessions', sa.Column('status', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sessions', 'status')
    op.drop_column('courses', 'is_archived')
    # ### end Alembic commands ###
