"""Add has_completed_onboarding to user_profiles

Revision ID: d14839085523
Revises: 598c4bc054ec
Create Date: 2025-07-29 16:00:52.117065

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd14839085523'
down_revision: Union[str, None] = '598c4bc054ec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profiles', sa.Column('has_completed_onboarding', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_profiles', 'has_completed_onboarding')
    # ### end Alembic commands ###
