global:
  scrape_interval: 30s  # Reduced from 15s to save memory/CPU
  evaluation_interval: 30s
  external_labels:
    monitor: 'fastapi-lite-1gb'

# Memory-optimized scraping for 1GB VM
scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 60s  # Prometheus self-monitoring less frequent
    static_configs:
      - targets: ['prometheus:9090']

  - job_name: 'fastapi-app'
    metrics_path: /metrics
    scrape_interval: 30s  # Essential app metrics
    static_configs:
      - targets: ['app:8000']
    # Keep only essential metrics to reduce memory usage
    metric_relabel_configs:
      - source_labels: [__name__]
        regex: 'http_requests_total|http_request_duration_.*|fastapi_.*|up|process_.*'
        action: keep
      # Drop high cardinality metrics to save memory
      - source_labels: [__name__]
        regex: '.*_bucket'
        target_label: __tmp_drop
        replacement: 'drop'
      - source_labels: [__tmp_drop]
        regex: 'drop'
        action: drop
